# Generated by Django 4.2.4 on 2023-09-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("garagem", "0002_veiculo_capa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veiculo",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="marca",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="capa",
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="modelo", to="garagem.categoria"
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="modelo", to="garagem.marca"
                    ),
                ),
            ],
            options={
                "verbose_name": "modelo",
                "verbose_name_plural": "modelos",
            },
        ),
        migrations.AddField(
            model_name="veiculo",
            name="capa",
            field=models.ManyToManyField(related_name="+", to="uploader.image"),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="modelo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="veiculos", to="garagem.modelo"
            ),
        ),
    ]
