# Generated by Django 4.2.4 on 2023-09-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0003_remove_veiculo_categoria_remove_veiculo_marca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="descricao",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
