# Generated by Django 4.1.7 on 2023-05-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0007_alter_veiculo_categoria_alter_veiculo_cor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name_plural': 'cores'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'veículo'},
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
